[[Faiss_CUDA]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "9e985679593de9ee6ba8be56b2ca4586bb1a03ab"
lazy = true
libc = "glibc"
os = "linux"

    [[Faiss_CUDA.download]]
    sha256 = "3342d42c6d9ceddb01306b02878e6419d634781d80a40b12294289c920a10958"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_CUDA_jll.jl/releases/download/Faiss_CUDA-v1.9.0+1/Faiss_CUDA.v1.9.0.x86_64-linux-gnu-cuda+11.8.tar.gz"
[[Faiss_CUDA]]
arch = "x86_64"
cuda = "12.1"
git-tree-sha1 = "ae2dd872b785cdb30908414f39baf70c7c6aaa3c"
lazy = true
libc = "glibc"
os = "linux"

    [[Faiss_CUDA.download]]
    sha256 = "3743f98d2e9f37bbfef645a8cbf1f44abfe96ca8b857446bf3af0b048cd310df"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_CUDA_jll.jl/releases/download/Faiss_CUDA-v1.9.0+1/Faiss_CUDA.v1.9.0.x86_64-linux-gnu-cuda+12.1.tar.gz"
